env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - http://host.docker.internal:5001/api/payments/webhook
    - http://host.docker.internal:5001/
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: http://host.docker.internal:5001/
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: testreport.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
